/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: ./swig/example.swg

package swig

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


extern void _wrap_Swig_free_swig_a554f9d4064ac9c4(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_swig_a554f9d4064ac9c4(swig_intgo arg1);
extern swig_intgo _wrap_RED_swig_a554f9d4064ac9c4(void);
extern swig_intgo _wrap_BLUE_swig_a554f9d4064ac9c4(void);
extern swig_intgo _wrap_GREEN_swig_a554f9d4064ac9c4(void);
extern uintptr_t _wrap_new_Foo_swig_a554f9d4064ac9c4(void);
extern swig_intgo _wrap_IMPULSE_Foo_swig_a554f9d4064ac9c4(void);
extern swig_intgo _wrap_WARP_Foo_swig_a554f9d4064ac9c4(void);
extern swig_intgo _wrap_LUDICROUS_Foo_swig_a554f9d4064ac9c4(void);
extern void _wrap_Foo_enum_test_swig_a554f9d4064ac9c4(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_delete_Foo_swig_a554f9d4064ac9c4(uintptr_t arg1);
extern void _wrap_enum_test_swig_a554f9d4064ac9c4(swig_intgo arg1, swig_intgo arg2);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_swig_a554f9d4064ac9c4(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_swig_a554f9d4064ac9c4(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type Color int
func _swig_getRED() (_swig_ret Color) {
	var swig_r Color
	swig_r = (Color)(C._wrap_RED_swig_a554f9d4064ac9c4())
	return swig_r
}

var RED Color = _swig_getRED()
func _swig_getBLUE() (_swig_ret Color) {
	var swig_r Color
	swig_r = (Color)(C._wrap_BLUE_swig_a554f9d4064ac9c4())
	return swig_r
}

var BLUE Color = _swig_getBLUE()
func _swig_getGREEN() (_swig_ret Color) {
	var swig_r Color
	swig_r = (Color)(C._wrap_GREEN_swig_a554f9d4064ac9c4())
	return swig_r
}

var GREEN Color = _swig_getGREEN()
type SwigcptrFoo uintptr

func (p SwigcptrFoo) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrFoo) SwigIsFoo() {
}

func NewFoo() (_swig_ret Foo) {
	var swig_r Foo
	swig_r = (Foo)(SwigcptrFoo(C._wrap_new_Foo_swig_a554f9d4064ac9c4()))
	return swig_r
}

type FooSpeed int
func _swig_getFoo_IMPULSE_Foo() (_swig_ret FooSpeed) {
	var swig_r FooSpeed
	swig_r = (FooSpeed)(C._wrap_IMPULSE_Foo_swig_a554f9d4064ac9c4())
	return swig_r
}

var FooIMPULSE FooSpeed = _swig_getFoo_IMPULSE_Foo()
func _swig_getFoo_WARP_Foo() (_swig_ret FooSpeed) {
	var swig_r FooSpeed
	swig_r = (FooSpeed)(C._wrap_WARP_Foo_swig_a554f9d4064ac9c4())
	return swig_r
}

var FooWARP FooSpeed = _swig_getFoo_WARP_Foo()
func _swig_getFoo_LUDICROUS_Foo() (_swig_ret FooSpeed) {
	var swig_r FooSpeed
	swig_r = (FooSpeed)(C._wrap_LUDICROUS_Foo_swig_a554f9d4064ac9c4())
	return swig_r
}

var FooLUDICROUS FooSpeed = _swig_getFoo_LUDICROUS_Foo()
func (arg1 SwigcptrFoo) Enum_test(arg2 FooSpeed) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Foo_enum_test_swig_a554f9d4064ac9c4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func DeleteFoo(arg1 Foo) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Foo_swig_a554f9d4064ac9c4(C.uintptr_t(_swig_i_0))
}

type Foo interface {
	Swigcptr() uintptr
	SwigIsFoo()
	Enum_test(arg2 FooSpeed)
}

func Enum_test(arg1 Color, arg2 FooSpeed) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_enum_test_swig_a554f9d4064ac9c4(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1))
}


