/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: ./swig/example.i

package swig

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _gostring_ swig_type_1;
extern void _wrap_Swig_free_swig_14d4564140847704(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_swig_14d4564140847704(swig_intgo arg1);
extern char _wrap_CCONST2_swig_14d4564140847704(void);
extern swig_type_1 _wrap_SCONST2_swig_14d4564140847704(void);
extern double _wrap_EXPR_swig_14d4564140847704(void);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_swig_14d4564140847704(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_swig_14d4564140847704(C.swig_intgo(_swig_i_0)))
	return swig_r
}

const ICONST int = 42
const FCONST float64 = 2.1828
const CCONST byte = 'x'
func _swig_getCCONST2() (_swig_ret byte) {
	var swig_r byte
	swig_r = (byte)(C._wrap_CCONST2_swig_14d4564140847704())
	return swig_r
}

var CCONST2 byte = _swig_getCCONST2()
const SCONST string = "Hello World"
func _swig_getSCONST2() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_SCONST2_swig_14d4564140847704()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

var SCONST2 string = _swig_getSCONST2()
func _swig_getEXPR() (_swig_ret float64) {
	var swig_r float64
	swig_r = (float64)(C._wrap_EXPR_swig_14d4564140847704())
	return swig_r
}

var EXPR float64 = _swig_getEXPR()
const Iconst int = 37
const Fconst float64 = 3.14

