/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: ./swig/example.i

#ifndef SWIG_swig_WRAP_H_
#define SWIG_swig_WRAP_H_

class Swig_memory;

class SwigDirector_Callback : public Callback
{
 public:
  SwigDirector_Callback(int swig_p);
  virtual ~SwigDirector_Callback();
  void _swig_upcall_run() {
    Callback::run();
  }
  virtual void run();
 private:
  intgo go_val;
  Swig_memory *swig_mem;
};

#endif
