// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: AMAServer.proto
#ifndef GRPC_AMAServer_2eproto__INCLUDED
#define GRPC_AMAServer_2eproto__INCLUDED

#include "AMAServer.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace AMA {

// import "google/protobuf/empty.proto";
// import "protoc-gen-openapiv2/options/annotations.proto";
//
class AMAServer final {
 public:
  static constexpr char const* service_full_name() {
    return "AMA.AMAServer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status MDOrderBook(::grpc::ClientContext* context, const ::AMA::MDOrderBookRequest& request, ::AMA::MDOrderBookResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AMA::MDOrderBookResponse>> AsyncMDOrderBook(::grpc::ClientContext* context, const ::AMA::MDOrderBookRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AMA::MDOrderBookResponse>>(AsyncMDOrderBookRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AMA::MDOrderBookResponse>> PrepareAsyncMDOrderBook(::grpc::ClientContext* context, const ::AMA::MDOrderBookRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AMA::MDOrderBookResponse>>(PrepareAsyncMDOrderBookRaw(context, request, cq));
    }
    // option (google.api.http) = {
    //   get : "/ama/mdorderbook" 
    //   body:"*"
    // };
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void MDOrderBook(::grpc::ClientContext* context, const ::AMA::MDOrderBookRequest* request, ::AMA::MDOrderBookResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void MDOrderBook(::grpc::ClientContext* context, const ::AMA::MDOrderBookRequest* request, ::AMA::MDOrderBookResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // option (google.api.http) = {
      //   get : "/ama/mdorderbook" 
      //   body:"*"
      // };
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::AMA::MDOrderBookResponse>* AsyncMDOrderBookRaw(::grpc::ClientContext* context, const ::AMA::MDOrderBookRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::AMA::MDOrderBookResponse>* PrepareAsyncMDOrderBookRaw(::grpc::ClientContext* context, const ::AMA::MDOrderBookRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status MDOrderBook(::grpc::ClientContext* context, const ::AMA::MDOrderBookRequest& request, ::AMA::MDOrderBookResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AMA::MDOrderBookResponse>> AsyncMDOrderBook(::grpc::ClientContext* context, const ::AMA::MDOrderBookRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AMA::MDOrderBookResponse>>(AsyncMDOrderBookRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AMA::MDOrderBookResponse>> PrepareAsyncMDOrderBook(::grpc::ClientContext* context, const ::AMA::MDOrderBookRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AMA::MDOrderBookResponse>>(PrepareAsyncMDOrderBookRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void MDOrderBook(::grpc::ClientContext* context, const ::AMA::MDOrderBookRequest* request, ::AMA::MDOrderBookResponse* response, std::function<void(::grpc::Status)>) override;
      void MDOrderBook(::grpc::ClientContext* context, const ::AMA::MDOrderBookRequest* request, ::AMA::MDOrderBookResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::AMA::MDOrderBookResponse>* AsyncMDOrderBookRaw(::grpc::ClientContext* context, const ::AMA::MDOrderBookRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::AMA::MDOrderBookResponse>* PrepareAsyncMDOrderBookRaw(::grpc::ClientContext* context, const ::AMA::MDOrderBookRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_MDOrderBook_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status MDOrderBook(::grpc::ServerContext* context, const ::AMA::MDOrderBookRequest* request, ::AMA::MDOrderBookResponse* response);
    // option (google.api.http) = {
    //   get : "/ama/mdorderbook" 
    //   body:"*"
    // };
  };
  template <class BaseClass>
  class WithAsyncMethod_MDOrderBook : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_MDOrderBook() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_MDOrderBook() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MDOrderBook(::grpc::ServerContext* /*context*/, const ::AMA::MDOrderBookRequest* /*request*/, ::AMA::MDOrderBookResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMDOrderBook(::grpc::ServerContext* context, ::AMA::MDOrderBookRequest* request, ::grpc::ServerAsyncResponseWriter< ::AMA::MDOrderBookResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_MDOrderBook<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_MDOrderBook : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_MDOrderBook() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::AMA::MDOrderBookRequest, ::AMA::MDOrderBookResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::AMA::MDOrderBookRequest* request, ::AMA::MDOrderBookResponse* response) { return this->MDOrderBook(context, request, response); }));}
    void SetMessageAllocatorFor_MDOrderBook(
        ::grpc::MessageAllocator< ::AMA::MDOrderBookRequest, ::AMA::MDOrderBookResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::AMA::MDOrderBookRequest, ::AMA::MDOrderBookResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_MDOrderBook() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MDOrderBook(::grpc::ServerContext* /*context*/, const ::AMA::MDOrderBookRequest* /*request*/, ::AMA::MDOrderBookResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* MDOrderBook(
      ::grpc::CallbackServerContext* /*context*/, const ::AMA::MDOrderBookRequest* /*request*/, ::AMA::MDOrderBookResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_MDOrderBook<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_MDOrderBook : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_MDOrderBook() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_MDOrderBook() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MDOrderBook(::grpc::ServerContext* /*context*/, const ::AMA::MDOrderBookRequest* /*request*/, ::AMA::MDOrderBookResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_MDOrderBook : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_MDOrderBook() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_MDOrderBook() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MDOrderBook(::grpc::ServerContext* /*context*/, const ::AMA::MDOrderBookRequest* /*request*/, ::AMA::MDOrderBookResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMDOrderBook(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_MDOrderBook : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_MDOrderBook() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->MDOrderBook(context, request, response); }));
    }
    ~WithRawCallbackMethod_MDOrderBook() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MDOrderBook(::grpc::ServerContext* /*context*/, const ::AMA::MDOrderBookRequest* /*request*/, ::AMA::MDOrderBookResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* MDOrderBook(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_MDOrderBook : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_MDOrderBook() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::AMA::MDOrderBookRequest, ::AMA::MDOrderBookResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::AMA::MDOrderBookRequest, ::AMA::MDOrderBookResponse>* streamer) {
                       return this->StreamedMDOrderBook(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_MDOrderBook() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status MDOrderBook(::grpc::ServerContext* /*context*/, const ::AMA::MDOrderBookRequest* /*request*/, ::AMA::MDOrderBookResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedMDOrderBook(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::AMA::MDOrderBookRequest,::AMA::MDOrderBookResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_MDOrderBook<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_MDOrderBook<Service > StreamedService;
};

}  // namespace AMA


#endif  // GRPC_AMAServer_2eproto__INCLUDED
