/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: ./swig/example.i

package swig

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


extern void _wrap_Swig_free_swig_168ab2d8dc679747(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_swig_168ab2d8dc679747(swig_intgo arg1);
extern swig_intgo _wrap_maxint_swig_168ab2d8dc679747(swig_intgo arg1, swig_intgo arg2);
extern double _wrap_maxdouble_swig_168ab2d8dc679747(double arg1, double arg2);
extern uintptr_t _wrap_new_vecint_swig_168ab2d8dc679747(swig_intgo arg1);
extern swig_voidp _wrap_vecint_get_swig_168ab2d8dc679747(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_vecint_set_swig_168ab2d8dc679747(uintptr_t arg1, swig_intgo arg2, swig_voidp arg3);
extern swig_intgo _wrap_vecint_getitem_swig_168ab2d8dc679747(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_vecint_setitem_swig_168ab2d8dc679747(uintptr_t arg1, swig_intgo arg2, swig_intgo arg3);
extern void _wrap_delete_vecint_swig_168ab2d8dc679747(uintptr_t arg1);
extern uintptr_t _wrap_new_vecdouble_swig_168ab2d8dc679747(swig_intgo arg1);
extern swig_voidp _wrap_vecdouble_get_swig_168ab2d8dc679747(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_vecdouble_set_swig_168ab2d8dc679747(uintptr_t arg1, swig_intgo arg2, swig_voidp arg3);
extern double _wrap_vecdouble_getitem_swig_168ab2d8dc679747(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_vecdouble_setitem_swig_168ab2d8dc679747(uintptr_t arg1, swig_intgo arg2, double arg3);
extern void _wrap_delete_vecdouble_swig_168ab2d8dc679747(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_swig_168ab2d8dc679747(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_swig_168ab2d8dc679747(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Maxint(arg1 int, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_maxint_swig_168ab2d8dc679747(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Maxdouble(arg1 float64, arg2 float64) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (float64)(C._wrap_maxdouble_swig_168ab2d8dc679747(C.double(_swig_i_0), C.double(_swig_i_1)))
	return swig_r
}

type SwigcptrVecint uintptr

func (p SwigcptrVecint) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrVecint) SwigIsVecint() {
}

func NewVecint(arg1 int) (_swig_ret Vecint) {
	var swig_r Vecint
	_swig_i_0 := arg1
	swig_r = (Vecint)(SwigcptrVecint(C._wrap_new_vecint_swig_168ab2d8dc679747(C.swig_intgo(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrVecint) Get(arg2 int) (_swig_ret *int) {
	var swig_r *int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (*int)(C._wrap_vecint_get_swig_168ab2d8dc679747(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrVecint) Set(arg2 int, arg3 *int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_vecint_set_swig_168ab2d8dc679747(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_voidp(_swig_i_2))
}

func (arg1 SwigcptrVecint) Getitem(arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_vecint_getitem_swig_168ab2d8dc679747(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrVecint) Setitem(arg2 int, arg3 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_vecint_setitem_swig_168ab2d8dc679747(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2))
}

func DeleteVecint(arg1 Vecint) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_vecint_swig_168ab2d8dc679747(C.uintptr_t(_swig_i_0))
}

type Vecint interface {
	Swigcptr() uintptr
	SwigIsVecint()
	Get(arg2 int) (_swig_ret *int)
	Set(arg2 int, arg3 *int)
	Getitem(arg2 int) (_swig_ret int)
	Setitem(arg2 int, arg3 int)
}

type SwigcptrVecdouble uintptr

func (p SwigcptrVecdouble) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrVecdouble) SwigIsVecdouble() {
}

func NewVecdouble(arg1 int) (_swig_ret Vecdouble) {
	var swig_r Vecdouble
	_swig_i_0 := arg1
	swig_r = (Vecdouble)(SwigcptrVecdouble(C._wrap_new_vecdouble_swig_168ab2d8dc679747(C.swig_intgo(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrVecdouble) Get(arg2 int) (_swig_ret *float64) {
	var swig_r *float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (*float64)(C._wrap_vecdouble_get_swig_168ab2d8dc679747(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrVecdouble) Set(arg2 int, arg3 *float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_vecdouble_set_swig_168ab2d8dc679747(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_voidp(_swig_i_2))
}

func (arg1 SwigcptrVecdouble) Getitem(arg2 int) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (float64)(C._wrap_vecdouble_getitem_swig_168ab2d8dc679747(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrVecdouble) Setitem(arg2 int, arg3 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_vecdouble_setitem_swig_168ab2d8dc679747(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.double(_swig_i_2))
}

func DeleteVecdouble(arg1 Vecdouble) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_vecdouble_swig_168ab2d8dc679747(C.uintptr_t(_swig_i_0))
}

type Vecdouble interface {
	Swigcptr() uintptr
	SwigIsVecdouble()
	Get(arg2 int) (_swig_ret *float64)
	Set(arg2 int, arg3 *float64)
	Getitem(arg2 int) (_swig_ret float64)
	Setitem(arg2 int, arg3 float64)
}


