/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: ./swig/example.i

#ifndef SWIG_swig_WRAP_H_
#define SWIG_swig_WRAP_H_

class Swig_memory;

class SwigDirector_FooBarAbstract : public FooBarAbstract
{
 public:
  SwigDirector_FooBarAbstract(int swig_p);
  virtual ~SwigDirector_FooBarAbstract();
  std::string _swig_upcall_Foo() {
    return FooBarAbstract::Foo();
  }
  virtual std::string Foo();
  virtual std::string Bar();
 private:
  intgo go_val;
  Swig_memory *swig_mem;
};

#endif
