/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: ./swig/example.i

package swig

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef void* swig_type_1;
typedef void* swig_type_2;
typedef void* swig_type_3;
typedef void* swig_type_4;
typedef void* swig_type_5;
typedef void* swig_type_6;
extern void _wrap_Swig_free_swig_86b666b4fd27e37a(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_swig_86b666b4fd27e37a(swig_intgo arg1);
extern swig_intgo _wrap_do_op_swig_86b666b4fd27e37a(swig_intgo arg1, swig_intgo arg2, swig_type_1 arg3);
extern swig_type_2 _wrap_ADD_swig_86b666b4fd27e37a(void);
extern swig_type_3 _wrap_SUB_swig_86b666b4fd27e37a(void);
extern swig_type_4 _wrap_MUL_swig_86b666b4fd27e37a(void);
extern void _wrap_funcvar_set_swig_86b666b4fd27e37a(swig_type_5 arg1);
extern swig_type_6 _wrap_funcvar_get_swig_86b666b4fd27e37a(void);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_swig_86b666b4fd27e37a(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_swig_86b666b4fd27e37a(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Do_op(arg1 int, arg2 int, arg3 _swig_fnptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_do_op_swig_86b666b4fd27e37a(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_type_1(_swig_i_2)))
	return swig_r
}

func _swig_getADD() (_swig_ret _swig_fnptr) {
	var swig_r _swig_fnptr
	swig_r = (_swig_fnptr)(C._wrap_ADD_swig_86b666b4fd27e37a())
	return swig_r
}

var ADD _swig_fnptr = _swig_getADD()
func _swig_getSUB() (_swig_ret _swig_fnptr) {
	var swig_r _swig_fnptr
	swig_r = (_swig_fnptr)(C._wrap_SUB_swig_86b666b4fd27e37a())
	return swig_r
}

var SUB _swig_fnptr = _swig_getSUB()
func _swig_getMUL() (_swig_ret _swig_fnptr) {
	var swig_r _swig_fnptr
	swig_r = (_swig_fnptr)(C._wrap_MUL_swig_86b666b4fd27e37a())
	return swig_r
}

var MUL _swig_fnptr = _swig_getMUL()
func SetFuncvar(arg1 _swig_fnptr) {
	_swig_i_0 := arg1
	C._wrap_funcvar_set_swig_86b666b4fd27e37a(C.swig_type_5(_swig_i_0))
}

func GetFuncvar() (_swig_ret _swig_fnptr) {
	var swig_r _swig_fnptr
	swig_r = (_swig_fnptr)(C._wrap_funcvar_get_swig_86b666b4fd27e37a())
	return swig_r
}


