/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: ./swig/example.i

#define SWIGMODULE swig
#define SWIG_DIRECTORS

#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef long long intgo;
typedef unsigned long long uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;




#define swiggo_size_assert_eq(x, y, name) typedef char name[(x-y)*(x-y)*-2+1];
#define swiggo_size_assert(t, n) swiggo_size_assert_eq(sizeof(t), n, swiggo_sizeof_##t##_is_not_##n)

swiggo_size_assert(char, 1)
swiggo_size_assert(short, 2)
swiggo_size_assert(int, 4)
typedef long long swiggo_long_long;
swiggo_size_assert(swiggo_long_long, 8)
swiggo_size_assert(float, 4)
swiggo_size_assert(double, 8)

#ifdef __cplusplus
extern "C" {
#endif
extern void crosscall2(void (*fn)(void *, int), void *, int);
extern char* _cgo_topofstack(void) __attribute__ ((weak));
extern void _cgo_allocate(void *, int);
extern void _cgo_panic(void *, int);
#ifdef __cplusplus
}
#endif

static char *_swig_topofstack() {
  if (_cgo_topofstack) {
    return _cgo_topofstack();
  } else {
    return 0;
  }
}

static void _swig_gopanic(const char *p) {
  struct {
    const char *p;
  } SWIGSTRUCTPACKED a;
  a.p = p;
  crosscall2(_cgo_panic, &a, (int) sizeof a);
}




#define SWIG_contract_assert(expr, msg) \
  if (!(expr)) { _swig_gopanic(msg); } else


static _gostring_ Swig_AllocateString(const char *p, size_t l) {
  _gostring_ ret;
  ret.p = (char*)malloc(l);
  memcpy(ret.p, p, l);
  ret.n = l;
  return ret;
}

/* -----------------------------------------------------------------------------
 * director_common.swg
 *
 * This file contains support for director classes which is common between
 * languages.
 * ----------------------------------------------------------------------------- */

/*
  Use -DSWIG_DIRECTOR_STATIC if you prefer to avoid the use of the
  'Swig' namespace. This could be useful for multi-modules projects.
*/
#ifdef SWIG_DIRECTOR_STATIC
/* Force anonymous (static) namespace */
#define Swig
#endif
/* -----------------------------------------------------------------------------
 * director.swg
 *
 * This file contains support for director classes so that Go proxy
 * methods can be called from C++.
 * ----------------------------------------------------------------------------- */

#include <exception>
#include <map>

namespace Swig {

  class DirectorException : public std::exception {
  };
}

/* Handle memory management for directors.  */

namespace {
  struct GCItem {
    virtual ~GCItem() {}
  };

  struct GCItem_var {
    GCItem_var(GCItem *item = 0) : _item(item) {
    }

    GCItem_var& operator=(GCItem *item) {
      GCItem *tmp = _item;
      _item = item;
      delete tmp;
      return *this;
    }

    ~GCItem_var() {
      delete _item;
    }

    GCItem* operator->() {
      return _item;
    }

    private:
      GCItem *_item;
  };

  template <typename Type>
  struct GCItem_T : GCItem {
    GCItem_T(Type *ptr) : _ptr(ptr) {
    }

    virtual ~GCItem_T() {
      delete _ptr;
    }

  private:
    Type *_ptr;
  };
}

class Swig_memory {
public:
  template <typename Type>
  void swig_acquire_pointer(Type* vptr) {
    if (vptr) {
      swig_owner[vptr] = new GCItem_T<Type>(vptr);
    }
  }
private:
  typedef std::map<void *, GCItem_var> swig_ownership_map;
  swig_ownership_map swig_owner;
};

template <typename Type>
static void swig_acquire_pointer(Swig_memory** pmem, Type* ptr) {
  if (!pmem) {
    *pmem = new Swig_memory;
  }
  (*pmem)->swig_acquire_pointer(ptr);
}

static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}


#include "example.h"


#include <vector>
#include <stdexcept>


#include <string>


// C++ director class methods.
#include "example_wrap.h"

SwigDirector_Employee::SwigDirector_Employee(int swig_p, char const *n)
    : Employee(n),
      go_val(swig_p), swig_mem(0)
{ }

extern "C" _gostring_ Swig_DirectorEmployee_callback_getTitle_swig_6b447ef8cfcee6cd(int);
std::string SwigDirector_Employee::getTitle() {
  _gostring_ result;
  
  std::string c_result;
  result = Swig_DirectorEmployee_callback_getTitle_swig_6b447ef8cfcee6cd(go_val);
  
  c_result.assign(result.p, result.n);
  free(result.p);
  
  return c_result;
}

extern "C" _gostring_ Swig_DirectorEmployee_callback_getName_swig_6b447ef8cfcee6cd(int);
std::string SwigDirector_Employee::getName() {
  _gostring_ result;
  
  std::string c_result;
  result = Swig_DirectorEmployee_callback_getName_swig_6b447ef8cfcee6cd(go_val);
  
  c_result.assign(result.p, result.n);
  free(result.p);
  
  return c_result;
}

extern "C" _gostring_ Swig_DirectorEmployee_callback_getPosition_swig_6b447ef8cfcee6cd(int);
std::string SwigDirector_Employee::getPosition() const {
  _gostring_ result;
  
  std::string c_result;
  result = Swig_DirectorEmployee_callback_getPosition_swig_6b447ef8cfcee6cd(go_val);
  
  c_result.assign(result.p, result.n);
  free(result.p);
  
  return c_result;
}

extern "C" void Swiggo_DeleteDirector_Employee_swig_6b447ef8cfcee6cd(intgo);
SwigDirector_Employee::~SwigDirector_Employee()
{
  Swiggo_DeleteDirector_Employee_swig_6b447ef8cfcee6cd(go_val);
  delete swig_mem;
}

SwigDirector_Manager::SwigDirector_Manager(int swig_p, char const *n)
    : Manager(n),
      go_val(swig_p), swig_mem(0)
{ }

extern "C" _gostring_ Swig_DirectorManager_callback_getTitle_swig_6b447ef8cfcee6cd(int);
std::string SwigDirector_Manager::getTitle() {
  _gostring_ result;
  
  std::string c_result;
  result = Swig_DirectorManager_callback_getTitle_swig_6b447ef8cfcee6cd(go_val);
  
  c_result.assign(result.p, result.n);
  free(result.p);
  
  return c_result;
}

extern "C" _gostring_ Swig_DirectorManager_callback_getName_swig_6b447ef8cfcee6cd(int);
std::string SwigDirector_Manager::getName() {
  _gostring_ result;
  
  std::string c_result;
  result = Swig_DirectorManager_callback_getName_swig_6b447ef8cfcee6cd(go_val);
  
  c_result.assign(result.p, result.n);
  free(result.p);
  
  return c_result;
}

extern "C" _gostring_ Swig_DirectorManager_callback_getPosition_swig_6b447ef8cfcee6cd(int);
std::string SwigDirector_Manager::getPosition() const {
  _gostring_ result;
  
  std::string c_result;
  result = Swig_DirectorManager_callback_getPosition_swig_6b447ef8cfcee6cd(go_val);
  
  c_result.assign(result.p, result.n);
  free(result.p);
  
  return c_result;
}

extern "C" void Swiggo_DeleteDirector_Manager_swig_6b447ef8cfcee6cd(intgo);
SwigDirector_Manager::~SwigDirector_Manager()
{
  Swiggo_DeleteDirector_Manager_swig_6b447ef8cfcee6cd(go_val);
  delete swig_mem;
}

#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_swig_6b447ef8cfcee6cd(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void *_wrap_Swig_malloc_swig_6b447ef8cfcee6cd(intgo _swig_go_0) {
  int arg1 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


Employee *_wrap__swig_NewDirectorEmployeeEmployee_swig_6b447ef8cfcee6cd(intgo _swig_go_0, _gostring_ _swig_go_1) {
  int arg1 ;
  char *arg2 = (char *) 0 ;
  Employee *result = 0 ;
  Employee *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = new SwigDirector_Employee(arg1, arg2);
  *(Employee **)&_swig_go_result = (Employee *)result; 
  free(arg2); 
  return _swig_go_result;
}


_gostring_ _wrap__swig_DirectorEmployee_upcall_GetTitle_swig_6b447ef8cfcee6cd(SwigDirector_Employee *_swig_go_0) {
  SwigDirector_Employee *arg1 = (SwigDirector_Employee *) 0 ;
  std::string result;
  _gostring_ _swig_go_result;
  
  arg1 = *(SwigDirector_Employee **)&_swig_go_0; 
  
  result = (std::string)arg1->_swig_upcall_getTitle();
  _swig_go_result = Swig_AllocateString((&result)->data(), (&result)->length()); 
  return _swig_go_result;
}


_gostring_ _wrap__swig_DirectorEmployee_upcall_GetName_swig_6b447ef8cfcee6cd(SwigDirector_Employee *_swig_go_0) {
  SwigDirector_Employee *arg1 = (SwigDirector_Employee *) 0 ;
  std::string result;
  _gostring_ _swig_go_result;
  
  arg1 = *(SwigDirector_Employee **)&_swig_go_0; 
  
  result = (std::string)arg1->_swig_upcall_getName();
  _swig_go_result = Swig_AllocateString((&result)->data(), (&result)->length()); 
  return _swig_go_result;
}


_gostring_ _wrap__swig_DirectorEmployee_upcall_GetPosition_swig_6b447ef8cfcee6cd(SwigDirector_Employee *_swig_go_0) {
  SwigDirector_Employee *arg1 = (SwigDirector_Employee *) 0 ;
  std::string result;
  _gostring_ _swig_go_result;
  
  arg1 = *(SwigDirector_Employee **)&_swig_go_0; 
  
  result = (std::string)arg1->_swig_upcall_getPosition();
  _swig_go_result = Swig_AllocateString((&result)->data(), (&result)->length()); 
  return _swig_go_result;
}


void _wrap_DeleteDirectorEmployee_swig_6b447ef8cfcee6cd(Employee *_swig_go_0) {
  Employee *arg1 = (Employee *) 0 ;
  
  arg1 = *(Employee **)&_swig_go_0; 
  
  delete arg1;
  
}


Employee *_wrap_new_Employee_swig_6b447ef8cfcee6cd(_gostring_ _swig_go_0) {
  char *arg1 = (char *) 0 ;
  Employee *result = 0 ;
  Employee *_swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  result = (Employee *)new Employee((char const *)arg1);
  *(Employee **)&_swig_go_result = (Employee *)result; 
  free(arg1); 
  return _swig_go_result;
}


_gostring_ _wrap_Employee_getTitle_swig_6b447ef8cfcee6cd(Employee *_swig_go_0) {
  Employee *arg1 = (Employee *) 0 ;
  std::string result;
  _gostring_ _swig_go_result;
  
  arg1 = *(Employee **)&_swig_go_0; 
  
  result = (arg1)->getTitle();
  _swig_go_result = Swig_AllocateString((&result)->data(), (&result)->length()); 
  return _swig_go_result;
}


_gostring_ _wrap_Employee_getName_swig_6b447ef8cfcee6cd(Employee *_swig_go_0) {
  Employee *arg1 = (Employee *) 0 ;
  std::string result;
  _gostring_ _swig_go_result;
  
  arg1 = *(Employee **)&_swig_go_0; 
  
  result = (arg1)->getName();
  _swig_go_result = Swig_AllocateString((&result)->data(), (&result)->length()); 
  return _swig_go_result;
}


_gostring_ _wrap_Employee_getPosition_swig_6b447ef8cfcee6cd(Employee *_swig_go_0) {
  Employee *arg1 = (Employee *) 0 ;
  std::string result;
  _gostring_ _swig_go_result;
  
  arg1 = *(Employee **)&_swig_go_0; 
  
  result = ((Employee const *)arg1)->getPosition();
  _swig_go_result = Swig_AllocateString((&result)->data(), (&result)->length()); 
  return _swig_go_result;
}


void _wrap_delete_Employee_swig_6b447ef8cfcee6cd(Employee *_swig_go_0) {
  Employee *arg1 = (Employee *) 0 ;
  
  arg1 = *(Employee **)&_swig_go_0; 
  
  delete arg1;
  
}


Manager *_wrap__swig_NewDirectorManagerManager_swig_6b447ef8cfcee6cd(intgo _swig_go_0, _gostring_ _swig_go_1) {
  int arg1 ;
  char *arg2 = (char *) 0 ;
  Manager *result = 0 ;
  Manager *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = new SwigDirector_Manager(arg1, arg2);
  *(Manager **)&_swig_go_result = (Manager *)result; 
  free(arg2); 
  return _swig_go_result;
}


_gostring_ _wrap__swig_DirectorManager_upcall_GetTitle_swig_6b447ef8cfcee6cd(SwigDirector_Manager *_swig_go_0) {
  SwigDirector_Manager *arg1 = (SwigDirector_Manager *) 0 ;
  std::string result;
  _gostring_ _swig_go_result;
  
  arg1 = *(SwigDirector_Manager **)&_swig_go_0; 
  
  result = (std::string)arg1->_swig_upcall_getTitle();
  _swig_go_result = Swig_AllocateString((&result)->data(), (&result)->length()); 
  return _swig_go_result;
}


_gostring_ _wrap__swig_DirectorManager_upcall_GetName_swig_6b447ef8cfcee6cd(SwigDirector_Manager *_swig_go_0) {
  SwigDirector_Manager *arg1 = (SwigDirector_Manager *) 0 ;
  std::string result;
  _gostring_ _swig_go_result;
  
  arg1 = *(SwigDirector_Manager **)&_swig_go_0; 
  
  result = (std::string)arg1->_swig_upcall_getName();
  _swig_go_result = Swig_AllocateString((&result)->data(), (&result)->length()); 
  return _swig_go_result;
}


_gostring_ _wrap__swig_DirectorManager_upcall_GetPosition_swig_6b447ef8cfcee6cd(SwigDirector_Manager *_swig_go_0) {
  SwigDirector_Manager *arg1 = (SwigDirector_Manager *) 0 ;
  std::string result;
  _gostring_ _swig_go_result;
  
  arg1 = *(SwigDirector_Manager **)&_swig_go_0; 
  
  result = (std::string)arg1->_swig_upcall_getPosition();
  _swig_go_result = Swig_AllocateString((&result)->data(), (&result)->length()); 
  return _swig_go_result;
}


void _wrap_DeleteDirectorManager_swig_6b447ef8cfcee6cd(Manager *_swig_go_0) {
  Manager *arg1 = (Manager *) 0 ;
  
  arg1 = *(Manager **)&_swig_go_0; 
  
  delete arg1;
  
}


Manager *_wrap_new_Manager_swig_6b447ef8cfcee6cd(_gostring_ _swig_go_0) {
  char *arg1 = (char *) 0 ;
  Manager *result = 0 ;
  Manager *_swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  result = (Manager *)new Manager((char const *)arg1);
  *(Manager **)&_swig_go_result = (Manager *)result; 
  free(arg1); 
  return _swig_go_result;
}


_gostring_ _wrap_Manager_getPosition_swig_6b447ef8cfcee6cd(Manager *_swig_go_0) {
  Manager *arg1 = (Manager *) 0 ;
  std::string result;
  _gostring_ _swig_go_result;
  
  arg1 = *(Manager **)&_swig_go_0; 
  
  result = ((Manager const *)arg1)->getPosition();
  _swig_go_result = Swig_AllocateString((&result)->data(), (&result)->length()); 
  return _swig_go_result;
}


void _wrap_delete_Manager_swig_6b447ef8cfcee6cd(Manager *_swig_go_0) {
  Manager *arg1 = (Manager *) 0 ;
  
  arg1 = *(Manager **)&_swig_go_0; 
  
  delete arg1;
  
}


_gostring_ _wrap_Manager_getTitle_swig_6b447ef8cfcee6cd(Manager *_swig_go_0) {
  Manager *arg1 = (Manager *) 0 ;
  std::string result;
  _gostring_ _swig_go_result;
  
  arg1 = *(Manager **)&_swig_go_0; 
  
  Employee *swig_b0 = (Employee *)arg1;
  result = (swig_b0)->getTitle();
  _swig_go_result = Swig_AllocateString((&result)->data(), (&result)->length()); 
  return _swig_go_result;
}


_gostring_ _wrap_Manager_getName_swig_6b447ef8cfcee6cd(Manager *_swig_go_0) {
  Manager *arg1 = (Manager *) 0 ;
  std::string result;
  _gostring_ _swig_go_result;
  
  arg1 = *(Manager **)&_swig_go_0; 
  
  Employee *swig_b0 = (Employee *)arg1;
  result = (swig_b0)->getName();
  _swig_go_result = Swig_AllocateString((&result)->data(), (&result)->length()); 
  return _swig_go_result;
}


EmployeeList *_wrap_new_EmployeeList_swig_6b447ef8cfcee6cd() {
  EmployeeList *result = 0 ;
  EmployeeList *_swig_go_result;
  
  
  result = (EmployeeList *)new EmployeeList();
  *(EmployeeList **)&_swig_go_result = (EmployeeList *)result; 
  return _swig_go_result;
}


void _wrap_EmployeeList_addEmployee_swig_6b447ef8cfcee6cd(EmployeeList *_swig_go_0, Employee *_swig_go_1) {
  EmployeeList *arg1 = (EmployeeList *) 0 ;
  Employee *arg2 = (Employee *) 0 ;
  
  arg1 = *(EmployeeList **)&_swig_go_0; 
  arg2 = *(Employee **)&_swig_go_1; 
  
  (arg1)->addEmployee(arg2);
  
}


Employee *_wrap_EmployeeList_get_item_swig_6b447ef8cfcee6cd(EmployeeList *_swig_go_0, intgo _swig_go_1) {
  EmployeeList *arg1 = (EmployeeList *) 0 ;
  int arg2 ;
  Employee *result = 0 ;
  Employee *_swig_go_result;
  
  arg1 = *(EmployeeList **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (Employee *)(arg1)->get_item(arg2);
  *(Employee **)&_swig_go_result = (Employee *)result; 
  return _swig_go_result;
}


void _wrap_delete_EmployeeList_swig_6b447ef8cfcee6cd(EmployeeList *_swig_go_0) {
  EmployeeList *arg1 = (EmployeeList *) 0 ;
  
  arg1 = *(EmployeeList **)&_swig_go_0; 
  
  delete arg1;
  
}


#ifdef __cplusplus
}
#endif

