/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: ./swig/example.i

package swig

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _gostring_ swig_type_1;
typedef _gostring_ swig_type_2;
typedef _gostring_ swig_type_3;
typedef _gostring_ swig_type_4;
typedef _gostring_ swig_type_5;
typedef _gostring_ swig_type_6;
typedef _gostring_ swig_type_7;
typedef _gostring_ swig_type_8;
typedef _gostring_ swig_type_9;
typedef _gostring_ swig_type_10;
typedef _gostring_ swig_type_11;
typedef _gostring_ swig_type_12;
typedef _gostring_ swig_type_13;
typedef _gostring_ swig_type_14;
extern void _wrap_Swig_free_swig_6b447ef8cfcee6cd(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_swig_6b447ef8cfcee6cd(swig_intgo arg1);
extern uintptr_t _wrap__swig_NewDirectorEmployeeEmployee_swig_6b447ef8cfcee6cd(int, swig_type_1 arg1);
extern swig_type_2 _wrap__swig_DirectorEmployee_upcall_GetTitle_swig_6b447ef8cfcee6cd(uintptr_t);
extern swig_type_3 _wrap__swig_DirectorEmployee_upcall_GetName_swig_6b447ef8cfcee6cd(uintptr_t);
extern swig_type_4 _wrap__swig_DirectorEmployee_upcall_GetPosition_swig_6b447ef8cfcee6cd(uintptr_t);
extern void _wrap_DeleteDirectorEmployee_swig_6b447ef8cfcee6cd(uintptr_t arg1);
extern uintptr_t _wrap_new_Employee_swig_6b447ef8cfcee6cd(swig_type_1 arg1);
extern swig_type_5 _wrap_Employee_getTitle_swig_6b447ef8cfcee6cd(uintptr_t arg1);
extern swig_type_6 _wrap_Employee_getName_swig_6b447ef8cfcee6cd(uintptr_t arg1);
extern swig_type_7 _wrap_Employee_getPosition_swig_6b447ef8cfcee6cd(uintptr_t arg1);
extern void _wrap_delete_Employee_swig_6b447ef8cfcee6cd(uintptr_t arg1);
extern uintptr_t _wrap__swig_NewDirectorManagerManager_swig_6b447ef8cfcee6cd(int, swig_type_8 arg1);
extern swig_type_9 _wrap__swig_DirectorManager_upcall_GetTitle_swig_6b447ef8cfcee6cd(uintptr_t);
extern swig_type_10 _wrap__swig_DirectorManager_upcall_GetName_swig_6b447ef8cfcee6cd(uintptr_t);
extern swig_type_11 _wrap__swig_DirectorManager_upcall_GetPosition_swig_6b447ef8cfcee6cd(uintptr_t);
extern void _wrap_DeleteDirectorManager_swig_6b447ef8cfcee6cd(uintptr_t arg1);
extern uintptr_t _wrap_new_Manager_swig_6b447ef8cfcee6cd(swig_type_8 arg1);
extern swig_type_12 _wrap_Manager_getPosition_swig_6b447ef8cfcee6cd(uintptr_t arg1);
extern void _wrap_delete_Manager_swig_6b447ef8cfcee6cd(uintptr_t arg1);
extern swig_type_13 _wrap_Manager_getTitle_swig_6b447ef8cfcee6cd(uintptr_t _swig_base);
extern swig_type_14 _wrap_Manager_getName_swig_6b447ef8cfcee6cd(uintptr_t _swig_base);
extern uintptr_t _wrap_new_EmployeeList_swig_6b447ef8cfcee6cd(void);
extern void _wrap_EmployeeList_addEmployee_swig_6b447ef8cfcee6cd(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_EmployeeList_get_item_swig_6b447ef8cfcee6cd(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_delete_EmployeeList_swig_6b447ef8cfcee6cd(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_swig_6b447ef8cfcee6cd(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_swig_6b447ef8cfcee6cd(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type _swig_DirectorEmployee struct {
	SwigcptrEmployee
	v interface{}
}

func (p *_swig_DirectorEmployee) Swigcptr() uintptr {
	return p.SwigcptrEmployee.Swigcptr()
}

func (p *_swig_DirectorEmployee) SwigIsEmployee() {
}

func (p *_swig_DirectorEmployee) DirectorInterface() interface{} {
	return p.v
}

func NewDirectorEmployee(v interface{}, arg1 string) Employee {
	p := &_swig_DirectorEmployee{0, v}
	_swig_i_0 := arg1
	p.SwigcptrEmployee = SwigcptrEmployee(C._wrap__swig_NewDirectorEmployeeEmployee_swig_6b447ef8cfcee6cd(C.int(swigDirectorAdd(p)), *(*C.swig_type_1)(unsafe.Pointer(&_swig_i_0))))
	if Swig_escape_always_false {
		Swig_escape_val = _swig_i_0
	}
	return p
}

type _swig_DirectorInterfaceEmployeeGetTitle interface {
	GetTitle() string
}

func (swig_p *_swig_DirectorEmployee) GetTitle() string {
	if swig_g, swig_ok := swig_p.v.(_swig_DirectorInterfaceEmployeeGetTitle); swig_ok {
		return swig_g.GetTitle()
	}
	var swig_r string
	swig_r_p := C._wrap__swig_DirectorEmployee_upcall_GetTitle_swig_6b447ef8cfcee6cd(C.uintptr_t(swig_p.SwigcptrEmployee))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func DirectorEmployeeGetTitle(p Employee) string {
	var swig_r string
	swig_r_p := C._wrap__swig_DirectorEmployee_upcall_GetTitle_swig_6b447ef8cfcee6cd(C.uintptr_t(p.(*_swig_DirectorEmployee).SwigcptrEmployee))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

//export Swig_DirectorEmployee_callback_getTitle_swig_6b447ef8cfcee6cd
func Swig_DirectorEmployee_callback_getTitle_swig_6b447ef8cfcee6cd(swig_c int) (swig_result string) {
	var swig_r string
	swig_p := swigDirectorLookup(swig_c).(*_swig_DirectorEmployee)
	swig_r = swig_p.GetTitle()
	var swig_r_1 string

  {
    p := Swig_malloc(len(swig_r))
    s := (*[1<<30]byte)(unsafe.Pointer(p))[:len(swig_r)]
    copy(s, swig_r)
    swig_r_1 = *(*string)(unsafe.Pointer(&s))
  }

	return swig_r_1
}

type _swig_DirectorInterfaceEmployeeGetName interface {
	GetName() string
}

func (swig_p *_swig_DirectorEmployee) GetName() string {
	if swig_g, swig_ok := swig_p.v.(_swig_DirectorInterfaceEmployeeGetName); swig_ok {
		return swig_g.GetName()
	}
	var swig_r string
	swig_r_p := C._wrap__swig_DirectorEmployee_upcall_GetName_swig_6b447ef8cfcee6cd(C.uintptr_t(swig_p.SwigcptrEmployee))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func DirectorEmployeeGetName(p Employee) string {
	var swig_r string
	swig_r_p := C._wrap__swig_DirectorEmployee_upcall_GetName_swig_6b447ef8cfcee6cd(C.uintptr_t(p.(*_swig_DirectorEmployee).SwigcptrEmployee))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

//export Swig_DirectorEmployee_callback_getName_swig_6b447ef8cfcee6cd
func Swig_DirectorEmployee_callback_getName_swig_6b447ef8cfcee6cd(swig_c int) (swig_result string) {
	var swig_r string
	swig_p := swigDirectorLookup(swig_c).(*_swig_DirectorEmployee)
	swig_r = swig_p.GetName()
	var swig_r_1 string

  {
    p := Swig_malloc(len(swig_r))
    s := (*[1<<30]byte)(unsafe.Pointer(p))[:len(swig_r)]
    copy(s, swig_r)
    swig_r_1 = *(*string)(unsafe.Pointer(&s))
  }

	return swig_r_1
}

type _swig_DirectorInterfaceEmployeeGetPosition interface {
	GetPosition() string
}

func (swig_p *_swig_DirectorEmployee) GetPosition() string {
	if swig_g, swig_ok := swig_p.v.(_swig_DirectorInterfaceEmployeeGetPosition); swig_ok {
		return swig_g.GetPosition()
	}
	var swig_r string
	swig_r_p := C._wrap__swig_DirectorEmployee_upcall_GetPosition_swig_6b447ef8cfcee6cd(C.uintptr_t(swig_p.SwigcptrEmployee))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func DirectorEmployeeGetPosition(p Employee) string {
	var swig_r string
	swig_r_p := C._wrap__swig_DirectorEmployee_upcall_GetPosition_swig_6b447ef8cfcee6cd(C.uintptr_t(p.(*_swig_DirectorEmployee).SwigcptrEmployee))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

//export Swig_DirectorEmployee_callback_getPosition_swig_6b447ef8cfcee6cd
func Swig_DirectorEmployee_callback_getPosition_swig_6b447ef8cfcee6cd(swig_c int) (swig_result string) {
	var swig_r string
	swig_p := swigDirectorLookup(swig_c).(*_swig_DirectorEmployee)
	swig_r = swig_p.GetPosition()
	var swig_r_1 string

  {
    p := Swig_malloc(len(swig_r))
    s := (*[1<<30]byte)(unsafe.Pointer(p))[:len(swig_r)]
    copy(s, swig_r)
    swig_r_1 = *(*string)(unsafe.Pointer(&s))
  }

	return swig_r_1
}

func DeleteDirectorEmployee(arg1 Employee) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_DeleteDirectorEmployee_swig_6b447ef8cfcee6cd(C.uintptr_t(_swig_i_0))
}

//export Swiggo_DeleteDirector_Employee_swig_6b447ef8cfcee6cd
func Swiggo_DeleteDirector_Employee_swig_6b447ef8cfcee6cd(c int) {
	swigDirectorLookup(c).(*_swig_DirectorEmployee).SwigcptrEmployee = 0
	swigDirectorDelete(c)
}

type SwigcptrEmployee uintptr

func (p SwigcptrEmployee) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrEmployee) SwigIsEmployee() {
}

func (p SwigcptrEmployee) DirectorInterface() interface{} {
	return nil
}

func NewEmployee(arg1 string) (_swig_ret Employee) {
	var swig_r Employee
	_swig_i_0 := arg1
	swig_r = (Employee)(SwigcptrEmployee(C._wrap_new_Employee_swig_6b447ef8cfcee6cd(*(*C.swig_type_1)(unsafe.Pointer(&_swig_i_0)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func (arg1 SwigcptrEmployee) GetTitle() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Employee_getTitle_swig_6b447ef8cfcee6cd(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrEmployee) GetName() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Employee_getName_swig_6b447ef8cfcee6cd(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrEmployee) GetPosition() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Employee_getPosition_swig_6b447ef8cfcee6cd(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func DeleteEmployee(arg1 Employee) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Employee_swig_6b447ef8cfcee6cd(C.uintptr_t(_swig_i_0))
}

type Employee interface {
	Swigcptr() uintptr
	SwigIsEmployee()
	DirectorInterface() interface{}
	GetTitle() (_swig_ret string)
	GetName() (_swig_ret string)
	GetPosition() (_swig_ret string)
}

type _swig_DirectorManager struct {
	SwigcptrManager
	v interface{}
}

func (p *_swig_DirectorManager) Swigcptr() uintptr {
	return p.SwigcptrManager.Swigcptr()
}

func (p *_swig_DirectorManager) SwigIsManager() {
}

func (p *_swig_DirectorManager) DirectorInterface() interface{} {
	return p.v
}

func NewDirectorManager(v interface{}, arg1 string) Manager {
	p := &_swig_DirectorManager{0, v}
	_swig_i_0 := arg1
	p.SwigcptrManager = SwigcptrManager(C._wrap__swig_NewDirectorManagerManager_swig_6b447ef8cfcee6cd(C.int(swigDirectorAdd(p)), *(*C.swig_type_8)(unsafe.Pointer(&_swig_i_0))))
	if Swig_escape_always_false {
		Swig_escape_val = _swig_i_0
	}
	return p
}

type _swig_DirectorInterfaceManagerGetTitle interface {
	GetTitle() string
}

func (swig_p *_swig_DirectorManager) GetTitle() string {
	if swig_g, swig_ok := swig_p.v.(_swig_DirectorInterfaceManagerGetTitle); swig_ok {
		return swig_g.GetTitle()
	}
	var swig_r string
	swig_r_p := C._wrap__swig_DirectorManager_upcall_GetTitle_swig_6b447ef8cfcee6cd(C.uintptr_t(swig_p.SwigcptrManager))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func DirectorManagerGetTitle(p Manager) string {
	var swig_r string
	swig_r_p := C._wrap__swig_DirectorManager_upcall_GetTitle_swig_6b447ef8cfcee6cd(C.uintptr_t(p.(*_swig_DirectorManager).SwigcptrManager))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

//export Swig_DirectorManager_callback_getTitle_swig_6b447ef8cfcee6cd
func Swig_DirectorManager_callback_getTitle_swig_6b447ef8cfcee6cd(swig_c int) (swig_result string) {
	var swig_r string
	swig_p := swigDirectorLookup(swig_c).(*_swig_DirectorManager)
	swig_r = swig_p.GetTitle()
	var swig_r_1 string

  {
    p := Swig_malloc(len(swig_r))
    s := (*[1<<30]byte)(unsafe.Pointer(p))[:len(swig_r)]
    copy(s, swig_r)
    swig_r_1 = *(*string)(unsafe.Pointer(&s))
  }

	return swig_r_1
}

type _swig_DirectorInterfaceManagerGetName interface {
	GetName() string
}

func (swig_p *_swig_DirectorManager) GetName() string {
	if swig_g, swig_ok := swig_p.v.(_swig_DirectorInterfaceManagerGetName); swig_ok {
		return swig_g.GetName()
	}
	var swig_r string
	swig_r_p := C._wrap__swig_DirectorManager_upcall_GetName_swig_6b447ef8cfcee6cd(C.uintptr_t(swig_p.SwigcptrManager))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func DirectorManagerGetName(p Manager) string {
	var swig_r string
	swig_r_p := C._wrap__swig_DirectorManager_upcall_GetName_swig_6b447ef8cfcee6cd(C.uintptr_t(p.(*_swig_DirectorManager).SwigcptrManager))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

//export Swig_DirectorManager_callback_getName_swig_6b447ef8cfcee6cd
func Swig_DirectorManager_callback_getName_swig_6b447ef8cfcee6cd(swig_c int) (swig_result string) {
	var swig_r string
	swig_p := swigDirectorLookup(swig_c).(*_swig_DirectorManager)
	swig_r = swig_p.GetName()
	var swig_r_1 string

  {
    p := Swig_malloc(len(swig_r))
    s := (*[1<<30]byte)(unsafe.Pointer(p))[:len(swig_r)]
    copy(s, swig_r)
    swig_r_1 = *(*string)(unsafe.Pointer(&s))
  }

	return swig_r_1
}

type _swig_DirectorInterfaceManagerGetPosition interface {
	GetPosition() string
}

func (swig_p *_swig_DirectorManager) GetPosition() string {
	if swig_g, swig_ok := swig_p.v.(_swig_DirectorInterfaceManagerGetPosition); swig_ok {
		return swig_g.GetPosition()
	}
	var swig_r string
	swig_r_p := C._wrap__swig_DirectorManager_upcall_GetPosition_swig_6b447ef8cfcee6cd(C.uintptr_t(swig_p.SwigcptrManager))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func DirectorManagerGetPosition(p Manager) string {
	var swig_r string
	swig_r_p := C._wrap__swig_DirectorManager_upcall_GetPosition_swig_6b447ef8cfcee6cd(C.uintptr_t(p.(*_swig_DirectorManager).SwigcptrManager))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

//export Swig_DirectorManager_callback_getPosition_swig_6b447ef8cfcee6cd
func Swig_DirectorManager_callback_getPosition_swig_6b447ef8cfcee6cd(swig_c int) (swig_result string) {
	var swig_r string
	swig_p := swigDirectorLookup(swig_c).(*_swig_DirectorManager)
	swig_r = swig_p.GetPosition()
	var swig_r_1 string

  {
    p := Swig_malloc(len(swig_r))
    s := (*[1<<30]byte)(unsafe.Pointer(p))[:len(swig_r)]
    copy(s, swig_r)
    swig_r_1 = *(*string)(unsafe.Pointer(&s))
  }

	return swig_r_1
}

func DeleteDirectorManager(arg1 Manager) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_DeleteDirectorManager_swig_6b447ef8cfcee6cd(C.uintptr_t(_swig_i_0))
}

//export Swiggo_DeleteDirector_Manager_swig_6b447ef8cfcee6cd
func Swiggo_DeleteDirector_Manager_swig_6b447ef8cfcee6cd(c int) {
	swigDirectorLookup(c).(*_swig_DirectorManager).SwigcptrManager = 0
	swigDirectorDelete(c)
}

type SwigcptrManager uintptr

func (p SwigcptrManager) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrManager) SwigIsManager() {
}

func (p SwigcptrManager) DirectorInterface() interface{} {
	return nil
}

func NewManager(arg1 string) (_swig_ret Manager) {
	var swig_r Manager
	_swig_i_0 := arg1
	swig_r = (Manager)(SwigcptrManager(C._wrap_new_Manager_swig_6b447ef8cfcee6cd(*(*C.swig_type_8)(unsafe.Pointer(&_swig_i_0)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func (arg1 SwigcptrManager) GetPosition() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Manager_getPosition_swig_6b447ef8cfcee6cd(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func DeleteManager(arg1 Manager) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Manager_swig_6b447ef8cfcee6cd(C.uintptr_t(_swig_i_0))
}

func (_swig_base SwigcptrManager) GetTitle() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_Manager_getTitle_swig_6b447ef8cfcee6cd(C.uintptr_t(_swig_base))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (_swig_base SwigcptrManager) GetName() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_Manager_getName_swig_6b447ef8cfcee6cd(C.uintptr_t(_swig_base))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (p SwigcptrManager) SwigIsEmployee() {
}

func (p SwigcptrManager) SwigGetEmployee() Employee {
	return SwigcptrEmployee(p.Swigcptr())
}

type Manager interface {
	Swigcptr() uintptr
	SwigIsManager()
	DirectorInterface() interface{}
	GetPosition() (_swig_ret string)
	GetTitle() (_swig_ret string)
	GetName() (_swig_ret string)
	SwigIsEmployee()
	SwigGetEmployee() Employee
}

type SwigcptrEmployeeList uintptr

func (p SwigcptrEmployeeList) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrEmployeeList) SwigIsEmployeeList() {
}

func NewEmployeeList() (_swig_ret EmployeeList) {
	var swig_r EmployeeList
	swig_r = (EmployeeList)(SwigcptrEmployeeList(C._wrap_new_EmployeeList_swig_6b447ef8cfcee6cd()))
	return swig_r
}

func (arg1 SwigcptrEmployeeList) AddEmployee(arg2 Employee) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_EmployeeList_addEmployee_swig_6b447ef8cfcee6cd(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrEmployeeList) Get_item(arg2 int) (_swig_ret Employee) {
	var swig_r Employee
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Employee)(SwigcptrEmployee(C._wrap_EmployeeList_get_item_swig_6b447ef8cfcee6cd(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))))
	return swig_r
}

func DeleteEmployeeList(arg1 EmployeeList) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_EmployeeList_swig_6b447ef8cfcee6cd(C.uintptr_t(_swig_i_0))
}

type EmployeeList interface {
	Swigcptr() uintptr
	SwigIsEmployeeList()
	AddEmployee(arg2 Employee)
	Get_item(arg2 int) (_swig_ret Employee)
}


type SwigcptrSwigDirector_Manager uintptr
type SwigDirector_Manager interface {
	Swigcptr() uintptr;
}
func (p SwigcptrSwigDirector_Manager) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrSwigDirector_Employee uintptr
type SwigDirector_Employee interface {
	Swigcptr() uintptr;
}
func (p SwigcptrSwigDirector_Employee) Swigcptr() uintptr {
	return uintptr(p)
}



var swigDirectorTrack struct {
	sync.Mutex
	m map[int]interface{}
	c int
}

func swigDirectorAdd(v interface{}) int {
	swigDirectorTrack.Lock()
	defer swigDirectorTrack.Unlock()
	if swigDirectorTrack.m == nil {
		swigDirectorTrack.m = make(map[int]interface{})
	}
	swigDirectorTrack.c++
	ret := swigDirectorTrack.c
	swigDirectorTrack.m[ret] = v
	return ret
}

func swigDirectorLookup(c int) interface{} {
	swigDirectorTrack.Lock()
	defer swigDirectorTrack.Unlock()
	ret := swigDirectorTrack.m[c]
	if ret == nil {
		panic("C++ director pointer not found (possible	use-after-free)")
	}
	return ret
}

func swigDirectorDelete(c int) {
	swigDirectorTrack.Lock()
	defer swigDirectorTrack.Unlock()
	if swigDirectorTrack.m[c] == nil {
		if c > swigDirectorTrack.c {
			panic("C++ director pointer invalid (possible memory corruption")
		} else {
			panic("C++ director pointer not found (possible use-after-free)")
		}
	}
	delete(swigDirectorTrack.m, c)
}


