// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: AMAServer.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MDOrderBookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqTime string `protobuf:"bytes,1,opt,name=req_time,json=reqTime,proto3" json:"req_time,omitempty"`
}

func (x *MDOrderBookRequest) Reset() {
	*x = MDOrderBookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AMAServer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MDOrderBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MDOrderBookRequest) ProtoMessage() {}

func (x *MDOrderBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AMAServer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MDOrderBookRequest.ProtoReflect.Descriptor instead.
func (*MDOrderBookRequest) Descriptor() ([]byte, []int) {
	return file_AMAServer_proto_rawDescGZIP(), []int{0}
}

func (x *MDOrderBookRequest) GetReqTime() string {
	if x != nil {
		return x.ReqTime
	}
	return ""
}

type MDOrderBookResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderBookVector []*MDOrderBook `protobuf:"bytes,1,rep,name=order_book_vector,json=orderBookVector,proto3" json:"order_book_vector,omitempty"`
}

func (x *MDOrderBookResponse) Reset() {
	*x = MDOrderBookResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AMAServer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MDOrderBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MDOrderBookResponse) ProtoMessage() {}

func (x *MDOrderBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_AMAServer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MDOrderBookResponse.ProtoReflect.Descriptor instead.
func (*MDOrderBookResponse) Descriptor() ([]byte, []int) {
	return file_AMAServer_proto_rawDescGZIP(), []int{1}
}

func (x *MDOrderBookResponse) GetOrderBookVector() []*MDOrderBook {
	if x != nil {
		return x.OrderBookVector
	}
	return nil
}

type MDOrderBook struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelNo        int32              `protobuf:"varint,1,opt,name=channel_no,json=channelNo,proto3" json:"channel_no,omitempty"`
	MarketType       int32              `protobuf:"varint,2,opt,name=market_type,json=marketType,proto3" json:"market_type,omitempty"`
	SecurityCode     string             `protobuf:"bytes,3,opt,name=security_code,json=securityCode,proto3" json:"security_code,omitempty"`
	LastTickTime     int64              `protobuf:"varint,4,opt,name=last_tick_time,json=lastTickTime,proto3" json:"last_tick_time,omitempty"`
	LastSnapshotTime int64              `protobuf:"varint,5,opt,name=last_snapshot_time,json=lastSnapshotTime,proto3" json:"last_snapshot_time,omitempty"`
	LastTickSeq      int64              `protobuf:"varint,6,opt,name=last_tick_seq,json=lastTickSeq,proto3" json:"last_tick_seq,omitempty"`
	BidOrderBook     []*MDOrderBookItem `protobuf:"bytes,7,rep,name=bid_order_book,json=bidOrderBook,proto3" json:"bid_order_book,omitempty"`
	OfferOrderBook   []*MDOrderBookItem `protobuf:"bytes,8,rep,name=offer_order_book,json=offerOrderBook,proto3" json:"offer_order_book,omitempty"`
}

func (x *MDOrderBook) Reset() {
	*x = MDOrderBook{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AMAServer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MDOrderBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MDOrderBook) ProtoMessage() {}

func (x *MDOrderBook) ProtoReflect() protoreflect.Message {
	mi := &file_AMAServer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MDOrderBook.ProtoReflect.Descriptor instead.
func (*MDOrderBook) Descriptor() ([]byte, []int) {
	return file_AMAServer_proto_rawDescGZIP(), []int{2}
}

func (x *MDOrderBook) GetChannelNo() int32 {
	if x != nil {
		return x.ChannelNo
	}
	return 0
}

func (x *MDOrderBook) GetMarketType() int32 {
	if x != nil {
		return x.MarketType
	}
	return 0
}

func (x *MDOrderBook) GetSecurityCode() string {
	if x != nil {
		return x.SecurityCode
	}
	return ""
}

func (x *MDOrderBook) GetLastTickTime() int64 {
	if x != nil {
		return x.LastTickTime
	}
	return 0
}

func (x *MDOrderBook) GetLastSnapshotTime() int64 {
	if x != nil {
		return x.LastSnapshotTime
	}
	return 0
}

func (x *MDOrderBook) GetLastTickSeq() int64 {
	if x != nil {
		return x.LastTickSeq
	}
	return 0
}

func (x *MDOrderBook) GetBidOrderBook() []*MDOrderBookItem {
	if x != nil {
		return x.BidOrderBook
	}
	return nil
}

func (x *MDOrderBook) GetOfferOrderBook() []*MDOrderBookItem {
	if x != nil {
		return x.OfferOrderBook
	}
	return nil
}

type MDOrderBookItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price  int64 `protobuf:"varint,1,opt,name=price,proto3" json:"price,omitempty"`
	Volume int64 `protobuf:"varint,2,opt,name=volume,proto3" json:"volume,omitempty"`
	// int64 order_queue_size=3;
	OrderQueue []int64 `protobuf:"varint,4,rep,packed,name=order_queue,json=orderQueue,proto3" json:"order_queue,omitempty"`
}

func (x *MDOrderBookItem) Reset() {
	*x = MDOrderBookItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AMAServer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MDOrderBookItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MDOrderBookItem) ProtoMessage() {}

func (x *MDOrderBookItem) ProtoReflect() protoreflect.Message {
	mi := &file_AMAServer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MDOrderBookItem.ProtoReflect.Descriptor instead.
func (*MDOrderBookItem) Descriptor() ([]byte, []int) {
	return file_AMAServer_proto_rawDescGZIP(), []int{3}
}

func (x *MDOrderBookItem) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MDOrderBookItem) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *MDOrderBookItem) GetOrderQueue() []int64 {
	if x != nil {
		return x.OrderQueue
	}
	return nil
}

var File_AMAServer_proto protoreflect.FileDescriptor

var file_AMAServer_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x41, 0x4d, 0x41, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x41, 0x4d, 0x41, 0x22, 0x2f, 0x0a, 0x12, 0x4d, 0x44, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08,
	0x72, 0x65, 0x71, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x72, 0x65, 0x71, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x53, 0x0a, 0x13, 0x4d, 0x44, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c,
	0x0a, 0x11, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x76, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x41, 0x4d, 0x41, 0x2e,
	0x4d, 0x44, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x0f, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x22, 0xe6, 0x02, 0x0a,
	0x0b, 0x4d, 0x44, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4e, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x6d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x0d,
	0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x24, 0x0a, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x74, 0x69, 0x63, 0x6b, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x54,
	0x69, 0x63, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x6c, 0x61, 0x73, 0x74, 0x5f,
	0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x10, 0x6c, 0x61, 0x73, 0x74, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x74, 0x69,
	0x63, 0x6b, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6c, 0x61,
	0x73, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x53, 0x65, 0x71, 0x12, 0x3a, 0x0a, 0x0e, 0x62, 0x69, 0x64,
	0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x07, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x41, 0x4d, 0x41, 0x2e, 0x4d, 0x44, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42,
	0x6f, 0x6f, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0c, 0x62, 0x69, 0x64, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x3e, 0x0a, 0x10, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x5f, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x41, 0x4d, 0x41, 0x2e, 0x4d, 0x44, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x6f,
	0x6b, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0e, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x22, 0x60, 0x0a, 0x0f, 0x4d, 0x44, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f,
	0x71, 0x75, 0x65, 0x75, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0a, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x51, 0x75, 0x65, 0x75, 0x65, 0x32, 0x4f, 0x0a, 0x09, 0x41, 0x4d, 0x41, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x12, 0x42, 0x0a, 0x0b, 0x4d, 0x44, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42,
	0x6f, 0x6f, 0x6b, 0x12, 0x17, 0x2e, 0x41, 0x4d, 0x41, 0x2e, 0x4d, 0x44, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x41,
	0x4d, 0x41, 0x2e, 0x4d, 0x44, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x29, 0x5a, 0x27, 0x2f, 0x6d, 0x6e, 0x74,
	0x2f, 0x65, 0x2f, 0x63, 0x70, 0x70, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x30, 0x30,
	0x31, 0x2f, 0x30, 0x31, 0x33, 0x5f, 0x61, 0x6d, 0x61, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x67, 0x6f,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_AMAServer_proto_rawDescOnce sync.Once
	file_AMAServer_proto_rawDescData = file_AMAServer_proto_rawDesc
)

func file_AMAServer_proto_rawDescGZIP() []byte {
	file_AMAServer_proto_rawDescOnce.Do(func() {
		file_AMAServer_proto_rawDescData = protoimpl.X.CompressGZIP(file_AMAServer_proto_rawDescData)
	})
	return file_AMAServer_proto_rawDescData
}

var file_AMAServer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_AMAServer_proto_goTypes = []interface{}{
	(*MDOrderBookRequest)(nil),  // 0: AMA.MDOrderBookRequest
	(*MDOrderBookResponse)(nil), // 1: AMA.MDOrderBookResponse
	(*MDOrderBook)(nil),         // 2: AMA.MDOrderBook
	(*MDOrderBookItem)(nil),     // 3: AMA.MDOrderBookItem
}
var file_AMAServer_proto_depIdxs = []int32{
	2, // 0: AMA.MDOrderBookResponse.order_book_vector:type_name -> AMA.MDOrderBook
	3, // 1: AMA.MDOrderBook.bid_order_book:type_name -> AMA.MDOrderBookItem
	3, // 2: AMA.MDOrderBook.offer_order_book:type_name -> AMA.MDOrderBookItem
	0, // 3: AMA.AMAServer.MDOrderBook:input_type -> AMA.MDOrderBookRequest
	1, // 4: AMA.AMAServer.MDOrderBook:output_type -> AMA.MDOrderBookResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_AMAServer_proto_init() }
func file_AMAServer_proto_init() {
	if File_AMAServer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_AMAServer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MDOrderBookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AMAServer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MDOrderBookResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AMAServer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MDOrderBook); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AMAServer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MDOrderBookItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_AMAServer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_AMAServer_proto_goTypes,
		DependencyIndexes: file_AMAServer_proto_depIdxs,
		MessageInfos:      file_AMAServer_proto_msgTypes,
	}.Build()
	File_AMAServer_proto = out.File
	file_AMAServer_proto_rawDesc = nil
	file_AMAServer_proto_goTypes = nil
	file_AMAServer_proto_depIdxs = nil
}
