/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: ./swig/example.swg

package swig

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef long long swig_type_1;
typedef long long swig_type_2;
typedef long long swig_type_3;
typedef long long swig_type_4;
typedef _gostring_ swig_type_5;
typedef _gostring_ swig_type_6;
typedef _gostring_ swig_type_7;
typedef _gostring_ swig_type_8;
typedef _gostring_ swig_type_9;
typedef _gostring_ swig_type_10;
typedef _gostring_ swig_type_11;
extern void _wrap_Swig_free_swig_ab7e22793a1a5d61(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_swig_ab7e22793a1a5d61(swig_intgo arg1);
extern void _wrap_ivar_set_swig_ab7e22793a1a5d61(swig_intgo arg1);
extern swig_intgo _wrap_ivar_get_swig_ab7e22793a1a5d61(void);
extern void _wrap_svar_set_swig_ab7e22793a1a5d61(short arg1);
extern short _wrap_svar_get_swig_ab7e22793a1a5d61(void);
extern void _wrap_lvar_set_swig_ab7e22793a1a5d61(swig_type_1 arg1);
extern swig_type_2 _wrap_lvar_get_swig_ab7e22793a1a5d61(void);
extern void _wrap_uivar_set_swig_ab7e22793a1a5d61(swig_intgo arg1);
extern swig_intgo _wrap_uivar_get_swig_ab7e22793a1a5d61(void);
extern void _wrap_usvar_set_swig_ab7e22793a1a5d61(short arg1);
extern short _wrap_usvar_get_swig_ab7e22793a1a5d61(void);
extern void _wrap_ulvar_set_swig_ab7e22793a1a5d61(swig_type_3 arg1);
extern swig_type_4 _wrap_ulvar_get_swig_ab7e22793a1a5d61(void);
extern void _wrap_scvar_set_swig_ab7e22793a1a5d61(char arg1);
extern char _wrap_scvar_get_swig_ab7e22793a1a5d61(void);
extern void _wrap_ucvar_set_swig_ab7e22793a1a5d61(char arg1);
extern char _wrap_ucvar_get_swig_ab7e22793a1a5d61(void);
extern void _wrap_cvar_set_swig_ab7e22793a1a5d61(char arg1);
extern char _wrap_cvar_get_swig_ab7e22793a1a5d61(void);
extern void _wrap_fvar_set_swig_ab7e22793a1a5d61(float arg1);
extern float _wrap_fvar_get_swig_ab7e22793a1a5d61(void);
extern void _wrap_dvar_set_swig_ab7e22793a1a5d61(double arg1);
extern double _wrap_dvar_get_swig_ab7e22793a1a5d61(void);
extern void _wrap_strvar_set_swig_ab7e22793a1a5d61(swig_type_5 arg1);
extern swig_type_6 _wrap_strvar_get_swig_ab7e22793a1a5d61(void);
extern swig_type_7 _wrap_cstrvar_get_swig_ab7e22793a1a5d61(void);
extern void _wrap_iptrvar_set_swig_ab7e22793a1a5d61(swig_voidp arg1);
extern swig_voidp _wrap_iptrvar_get_swig_ab7e22793a1a5d61(void);
extern void _wrap_name_set_swig_ab7e22793a1a5d61(swig_type_8 arg1);
extern swig_type_9 _wrap_name_get_swig_ab7e22793a1a5d61(void);
extern void _wrap_ptptr_set_swig_ab7e22793a1a5d61(uintptr_t arg1);
extern uintptr_t _wrap_ptptr_get_swig_ab7e22793a1a5d61(void);
extern void _wrap_pt_set_swig_ab7e22793a1a5d61(uintptr_t arg1);
extern uintptr_t _wrap_pt_get_swig_ab7e22793a1a5d61(void);
extern swig_intgo _wrap_status_get_swig_ab7e22793a1a5d61(void);
extern swig_type_10 _wrap_path_get_swig_ab7e22793a1a5d61(void);
extern void _wrap_print_vars_swig_ab7e22793a1a5d61(void);
extern swig_voidp _wrap_new_int_swig_ab7e22793a1a5d61(swig_intgo arg1);
extern uintptr_t _wrap_new_Point_swig_ab7e22793a1a5d61(swig_intgo arg1, swig_intgo arg2);
extern swig_type_11 _wrap_Point_print_swig_ab7e22793a1a5d61(uintptr_t arg1);
extern void _wrap_pt_print_swig_ab7e22793a1a5d61(void);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_swig_ab7e22793a1a5d61(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_swig_ab7e22793a1a5d61(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func SetIvar(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_ivar_set_swig_ab7e22793a1a5d61(C.swig_intgo(_swig_i_0))
}

func GetIvar() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_ivar_get_swig_ab7e22793a1a5d61())
	return swig_r
}

func SetSvar(arg1 int16) {
	_swig_i_0 := arg1
	C._wrap_svar_set_swig_ab7e22793a1a5d61(C.short(_swig_i_0))
}

func GetSvar() (_swig_ret int16) {
	var swig_r int16
	swig_r = (int16)(C._wrap_svar_get_swig_ab7e22793a1a5d61())
	return swig_r
}

func SetLvar(arg1 int64) {
	_swig_i_0 := arg1
	C._wrap_lvar_set_swig_ab7e22793a1a5d61(C.swig_type_1(_swig_i_0))
}

func GetLvar() (_swig_ret int64) {
	var swig_r int64
	swig_r = (int64)(C._wrap_lvar_get_swig_ab7e22793a1a5d61())
	return swig_r
}

func SetUivar(arg1 uint) {
	_swig_i_0 := arg1
	C._wrap_uivar_set_swig_ab7e22793a1a5d61(C.swig_intgo(_swig_i_0))
}

func GetUivar() (_swig_ret uint) {
	var swig_r uint
	swig_r = (uint)(C._wrap_uivar_get_swig_ab7e22793a1a5d61())
	return swig_r
}

func SetUsvar(arg1 uint16) {
	_swig_i_0 := arg1
	C._wrap_usvar_set_swig_ab7e22793a1a5d61(C.short(_swig_i_0))
}

func GetUsvar() (_swig_ret uint16) {
	var swig_r uint16
	swig_r = (uint16)(C._wrap_usvar_get_swig_ab7e22793a1a5d61())
	return swig_r
}

func SetUlvar(arg1 uint64) {
	_swig_i_0 := arg1
	C._wrap_ulvar_set_swig_ab7e22793a1a5d61(C.swig_type_3(_swig_i_0))
}

func GetUlvar() (_swig_ret uint64) {
	var swig_r uint64
	swig_r = (uint64)(C._wrap_ulvar_get_swig_ab7e22793a1a5d61())
	return swig_r
}

func SetScvar(arg1 int8) {
	_swig_i_0 := arg1
	C._wrap_scvar_set_swig_ab7e22793a1a5d61(C.char(_swig_i_0))
}

func GetScvar() (_swig_ret int8) {
	var swig_r int8
	swig_r = (int8)(C._wrap_scvar_get_swig_ab7e22793a1a5d61())
	return swig_r
}

func SetUcvar(arg1 byte) {
	_swig_i_0 := arg1
	C._wrap_ucvar_set_swig_ab7e22793a1a5d61(C.char(_swig_i_0))
}

func GetUcvar() (_swig_ret byte) {
	var swig_r byte
	swig_r = (byte)(C._wrap_ucvar_get_swig_ab7e22793a1a5d61())
	return swig_r
}

func SetCvar(arg1 byte) {
	_swig_i_0 := arg1
	C._wrap_cvar_set_swig_ab7e22793a1a5d61(C.char(_swig_i_0))
}

func GetCvar() (_swig_ret byte) {
	var swig_r byte
	swig_r = (byte)(C._wrap_cvar_get_swig_ab7e22793a1a5d61())
	return swig_r
}

func SetFvar(arg1 float32) {
	_swig_i_0 := arg1
	C._wrap_fvar_set_swig_ab7e22793a1a5d61(C.float(_swig_i_0))
}

func GetFvar() (_swig_ret float32) {
	var swig_r float32
	swig_r = (float32)(C._wrap_fvar_get_swig_ab7e22793a1a5d61())
	return swig_r
}

func SetDvar(arg1 float64) {
	_swig_i_0 := arg1
	C._wrap_dvar_set_swig_ab7e22793a1a5d61(C.double(_swig_i_0))
}

func GetDvar() (_swig_ret float64) {
	var swig_r float64
	swig_r = (float64)(C._wrap_dvar_get_swig_ab7e22793a1a5d61())
	return swig_r
}

func SetStrvar(arg1 string) {
	_swig_i_0 := arg1
	C._wrap_strvar_set_swig_ab7e22793a1a5d61(*(*C.swig_type_5)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
}

func GetStrvar() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_strvar_get_swig_ab7e22793a1a5d61()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func GetCstrvar() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_cstrvar_get_swig_ab7e22793a1a5d61()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func SetIptrvar(arg1 *int) {
	_swig_i_0 := arg1
	C._wrap_iptrvar_set_swig_ab7e22793a1a5d61(C.swig_voidp(_swig_i_0))
}

func GetIptrvar() (_swig_ret *int) {
	var swig_r *int
	swig_r = (*int)(C._wrap_iptrvar_get_swig_ab7e22793a1a5d61())
	return swig_r
}

func SetName(arg1 string) {
	_swig_i_0 := arg1
	C._wrap_name_set_swig_ab7e22793a1a5d61(*(*C.swig_type_8)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
}

func GetName() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_name_get_swig_ab7e22793a1a5d61()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func SetPtptr(arg1 Point) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_ptptr_set_swig_ab7e22793a1a5d61(C.uintptr_t(_swig_i_0))
}

func GetPtptr() (_swig_ret Point) {
	var swig_r Point
	swig_r = (Point)(SwigcptrPoint(C._wrap_ptptr_get_swig_ab7e22793a1a5d61()))
	return swig_r
}

func SetPt(arg1 Point) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_pt_set_swig_ab7e22793a1a5d61(C.uintptr_t(_swig_i_0))
}

func GetPt() (_swig_ret Point) {
	var swig_r Point
	swig_r = (Point)(SwigcptrPoint(C._wrap_pt_get_swig_ab7e22793a1a5d61()))
	return swig_r
}

func GetStatus() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_status_get_swig_ab7e22793a1a5d61())
	return swig_r
}

func GetPath() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_path_get_swig_ab7e22793a1a5d61()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Print_vars() {
	C._wrap_print_vars_swig_ab7e22793a1a5d61()
}

func New_int(arg1 int) (_swig_ret *int) {
	var swig_r *int
	_swig_i_0 := arg1
	swig_r = (*int)(C._wrap_new_int_swig_ab7e22793a1a5d61(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func New_Point(arg1 int, arg2 int) (_swig_ret Point) {
	var swig_r Point
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Point)(SwigcptrPoint(C._wrap_new_Point_swig_ab7e22793a1a5d61(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1))))
	return swig_r
}

func Point_print(arg1 Point) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	swig_r_p := C._wrap_Point_print_swig_ab7e22793a1a5d61(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Pt_print() {
	C._wrap_pt_print_swig_ab7e22793a1a5d61()
}


type SwigcptrPoint uintptr
type Point interface {
	Swigcptr() uintptr;
}
func (p SwigcptrPoint) Swigcptr() uintptr {
	return uintptr(p)
}

